# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "fplongbeach.com" # the subpath of your site, e.g. /blog/
url: "www.fplongbeach.com" # the base hostname & protocol for your site
